window.D4_NEWS_ARTICLES = [
  {
    id: 'season-of-slaughter',
    slug: 'news-season-of-slaughter.html',
    title: 'Season of Slaughter launch guide',
    headline: 'Season of Slaughter is the headline story, and it changes what players should prioritize first',
    excerpt: 'This article breaks down the March 11 launch, Butcher powers, Bloodied Items, and why speed, momentum, and follow-up build pages matter more now.',
    archiveExcerpt: 'What changed, what players should care about first, and where to go next after reading the official announcement.',
    category: 'Season',
    categoryLabel: 'Season 12',
    date: '2026-03-05',
    dateLabel: 'March 5, 2026',
    readTime: '6 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/70/705XFJANQLC51772692144389.png',
    alt: 'Season of Slaughter official artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24244648/become-the-butcher-in-season-of-slaughter',
    priority: 100,
    homepageFeatured: true,
    searchText: 'season 12 slaughter butcher bloodied items paladin free trial fresh meat killstreak',
  },
  {
    id: 'patch-2-6',
    slug: 'news-patch-2-6.html',
    title: 'Patch 2.6 at a glance',
    headline: 'Patch 2.6 is the practical systems guide for Season of Slaughter players',
    excerpt: 'Blizzard\'s live patch notes confirm Bloodstained Sigils, new uniques from the Butcher Lair Boss, faster stagger windows, and a stronger reward loop for the new season.',
    archiveExcerpt: 'The key patch-note takeaways for players who want to understand how Season 12 actually plays.',
    category: 'Patch Notes',
    categoryLabel: 'Patch Notes',
    date: '2026-03-11',
    dateLabel: 'March 11, 2026',
    readTime: '5 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/aa/AAMRI1VFILVD1726179420079.png',
    alt: 'Diablo IV patch notes artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24266869/diablo-iv-patch-notes',
    priority: 95,
    searchText: 'patch 2.6 bloodstained sigils butcher lair boss uniques stagger killstreak season 12',
  },
  {
    id: 'warlock',
    slug: 'news-warlock.html',
    title: 'Warlock reveal summary',
    headline: 'What Blizzard has officially confirmed about Warlock',
    excerpt: 'A tight summary of the new class, release timing, and what is actually confirmed right now.',
    archiveExcerpt: 'A short class-focused summary covering timing, fantasy, and what the reveal means for the site.',
    category: 'Classes',
    categoryLabel: 'Class Reveal',
    date: '2026-03-05',
    dateLabel: 'March 5, 2026',
    readTime: '4 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/00/00LGKINJC4UD1772733022787.png',
    alt: 'Warlock official artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24267728/master-hell-itself-with-the-warlock',
    priority: 92,
    searchText: 'warlock reveal class lord of hatred demonic caster class fantasy',
  },
  {
    id: 'dev-livestream',
    slug: 'news-dev-livestream.html',
    title: 'Developer livestream watch guide',
    headline: 'The March developer livestream mattered because it previewed both Warlock and the next season at once',
    excerpt: 'Blizzard lined up Warlock details, season reveals, and Twitch Drops in one update stream, which made it one of the most useful pre-launch touchpoints for active players.',
    archiveExcerpt: 'Why the March 5 developer stream was a high-signal event for Warlock and Season 12 prep.',
    category: 'Community',
    categoryLabel: 'Livestream',
    date: '2026-03-02',
    dateLabel: 'March 2, 2026',
    readTime: '4 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/si/SIDHPPZKKISX1772472620411.png',
    alt: 'Developer update livestream artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24265936/join-our-next-developer-update-livestream',
    priority: 88,
    searchText: 'developer livestream warlock season 12 twitch drops omen glimpse wand scythe',
  },
  {
    id: 'patch-2-5',
    slug: 'news-patch-2-5.html',
    title: 'How to read Patch 2.5 without getting lost',
    headline: 'Patch 2.5 remains the systems reference point for current balance and feature changes',
    excerpt: 'A player-focused summary of the patch page and why it still matters when you are choosing resources or judging older guides.',
    archiveExcerpt: 'A utility-first guide to the current patch page so users know which parts matter for real decision-making.',
    category: 'Patch Notes',
    categoryLabel: 'Patch Notes',
    date: '2026-01-28',
    dateLabel: 'January 28, 2026',
    readTime: '4 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/dw/DWQ2XQCI8XR71681262808436.png',
    alt: 'Patch notes official artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24244466/diablo-iv-patch-notes-2-5',
    priority: 85,
    searchText: 'patch 2.5 notes balance systems reference changes live game',
  },
  {
    id: 'lord-of-hatred',
    slug: 'news-lord-of-hatred.html',
    title: 'Lord of Hatred: what is confirmed now',
    headline: 'Lord of Hatred is the big medium-term story, and Blizzard has now confirmed the release frame and several headline features',
    excerpt: 'A player-readable summary of the expansion page, new region, classes, and system updates.',
    archiveExcerpt: 'A tighter, player-readable summary of the official expansion page and the features that matter most.',
    category: 'Expansion',
    categoryLabel: 'Expansion',
    date: '2026-03-20',
    dateLabel: 'Updated March 2026',
    readTime: '5 min read',
    image: 'https://blz-contentstack-images.akamaized.net/v3/assets/blt9c12f249ac15c7ec/blt8409c2ec7041566a/6926318af4fa3f127a019f8a/D4_X2_OG.png?format=webp',
    alt: 'Lord of Hatred official artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://diablo4.blizzard.com/en-us/lord-of-hatred',
    priority: 82,
    searchText: 'lord of hatred expansion skovos mephisto paladin warlock release date',
  },
  {
    id: 'prepurchase-lord-of-hatred',
    slug: 'news-prepurchase-lord-of-hatred.html',
    title: 'What the Lord of Hatred pre-purchase actually gives players',
    headline: 'The pre-purchase page matters because it bundles the expansion pitch with immediate Paladin access and account upgrades',
    excerpt: 'Blizzard\'s pre-purchase post confirms that Paladin can be played immediately and frames the Age of Hatred collection as the onboarding option for new players.',
    archiveExcerpt: 'A practical read of the pre-purchase bundles, immediate unlocks, and who each edition is for.',
    category: 'Expansion',
    categoryLabel: 'Expansion',
    date: '2025-12-12',
    dateLabel: 'December 12, 2025',
    readTime: '4 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/5q/5QY0CPM6VA6T1765301004122.png',
    alt: 'Lord of Hatred pre-purchase artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24247511/stand-against-mephisto-pre-purchase-lord-of-hatred',
    priority: 78,
    searchText: 'pre purchase lord of hatred paladin today age of hatred collection stash tabs character slots',
  },
  {
    id: 'roadmap-2025',
    slug: 'news-roadmap-2025.html',
    title: 'Why the 2025 roadmap still matters',
    headline: 'The 2025 roadmap still explains how Blizzard framed the path from Belial and Horadrim content into the 2026 expansion cycle',
    excerpt: 'Even after later announcements, the roadmap is still useful because it shows Blizzard\'s seasonal intent, its quality-of-life priorities, and the build-up to expansion year.',
    archiveExcerpt: 'A short read on the roadmap items that still help players understand the bigger direction of the game.',
    category: 'Roadmap',
    categoryLabel: 'Roadmap',
    date: '2025-04-08',
    dateLabel: 'April 8, 2025',
    readTime: '4 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/6z/6ZXTVEYE6KYN1743724597239.png',
    alt: 'Diablo IV 2025 roadmap artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24189529/the-age-of-hatred-persists-diablo-iv-2025-roadmap',
    priority: 72,
    searchText: '2025 roadmap belial sins of the horadrim infernal chaos battle pass seasonal journey',
  },
  {
    id: 'mothers-blessing-march',
    slug: 'news-mothers-blessing-march.html',
    title: 'Mother’s Blessing week is still the easiest power-leveling reminder',
    headline: 'Mother’s Blessing is exactly the kind of event players should use to level alts, stack gold, and clear tree caches quickly',
    excerpt: 'Blizzard confirmed a March event window with bonus Gift of the Tree caches, 35% experience, and 50% gold, which is the kind of short-term boost resource sites should surface clearly.',
    archiveExcerpt: 'A quick event guide for players who want to use bonus XP and Tree caches efficiently.',
    category: 'Events',
    categoryLabel: 'Event',
    date: '2025-03-13',
    dateLabel: 'March 13, 2025',
    readTime: '3 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/9m/9MK56MC8W05S1741653109807.png',
    alt: 'Mother’s Blessing official artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24188043/mothers-blessing-returns-in-march',
    priority: 70,
    searchText: 'mother blessing xp gold tree caches gifts tree whispers event',
  },
  {
    id: 'gilded-goblins',
    slug: 'news-gilded-goblins.html',
    title: 'March of the Goblins was more than a loot novelty',
    headline: 'Gilded Goblins mattered because Blizzard added six new goblin variants and kept them in the game after the event window',
    excerpt: 'This was one of the most useful seasonal event posts because it changed loot expectations, introduced new goblin types, and rewarded targeted farming during the active week.',
    archiveExcerpt: 'A quick read on the goblin variants, the event window, and why players still care about the permanent additions.',
    category: 'Events',
    categoryLabel: 'Event',
    date: '2025-02-27',
    dateLabel: 'February 27, 2025',
    readTime: '4 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/zr/ZR0WOJNUIKG21740529670998.png',
    alt: 'Gilded Goblins event artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24177979/gilded-goblins-galore',
    priority: 68,
    searchText: 'gilded goblins march of the goblins treasure goblin variants mythic unique resplendent spark',
  },
  {
    id: 'ptr-2-4',
    slug: 'news-ptr-2-4.html',
    title: 'Why the 2.4.0 PTR mattered',
    headline: 'The 2.4.0 PTR mattered because Blizzard used it to preview Chaos Powers, Escalating Nightmares, and a higher-risk seasonal loop',
    excerpt: 'Blizzard’s August 14, 2025 PTR post previewed Chaos Armor, Chaos Powers, Escalating Nightmares, and a PTR reward track, making it one of the clearest “future systems” signals in the archive.',
    archiveExcerpt: 'A concise summary of the 2.4.0 PTR and the systems Blizzard used it to test before the next seasonal cycle.',
    category: 'PTR',
    categoryLabel: 'PTR',
    date: '2025-08-14',
    dateLabel: 'August 14, 2025',
    readTime: '4 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/vk/VKO0FT9QY1YS1754699164594.png',
    alt: 'Diablo IV 2.4.0 PTR artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/article/24224180/the-2-4-0-ptr-what-you-need-to-know',
    priority: 66,
    searchText: '2.4 ptr chaos armor chaos powers escalating nightmares ptr rewards',
  },
  {
    id: 'campfire-2-1-ptr',
    slug: 'news-campfire-2-1-ptr.html',
    title: 'Why the 2.1 PTR Campfire Chat was worth watching',
    headline: 'The 2.1 PTR Campfire Chat was useful because it translated PTR notes into player language before the patch landed',
    excerpt: 'Blizzard’s November 21, 2024 Campfire recap helped players understand the 2.1 PTR direction, which is exactly the type of context a newsroom should preserve instead of letting disappear into old VODs.',
    archiveExcerpt: 'A short read on why Campfire Chat recaps matter when PTR notes alone don’t tell the whole story.',
    category: 'Community',
    categoryLabel: 'Campfire Chat',
    date: '2024-11-21',
    dateLabel: 'November 21, 2024',
    readTime: '3 min read',
    image: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/6z/6Z93QEBB2FDD1731101934034.png',
    alt: 'Diablo IV Campfire Chat artwork',
    sourceName: 'Blizzard Entertainment',
    sourceUrl: 'https://news.blizzard.com/en-us/diablo4/24151774/catch-up-on-the-2-1-ptr-campfire-chat',
    priority: 60,
    searchText: 'campfire chat 2.1 ptr recap developer discussion systems preview',
  },
];
